### PR TITLE
Group Members Size

### PR DESCRIPTION
**Pull request by MatkoTom**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.

Implemented displaying number of users in a group under the group name.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration. All testing was done
manually by following, plainly, functionality requirements. If there are some special edge cases or
special ways that things need to be tested they will be mentioned below.

Dev testing

**Test Configuration**:

* Firmware version: G980FXXSFFVHA
* Hardware: SAMSUNG Galaxy S20
* SDK: Android 13

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

JPEG_20230810_104653_3286132844046226159
JPEG_20230810_104959_3986250186983716794

### CODE REVIEW

**Comment by ibencetic-CS** [comment]
Screenshot 2023-08-10 at 09 21 10

Looking at the figma screens, group name and any text under should not be the same size.

**Comment by MatkoTom** [comment]
> Screenshot 2023-08-10 at 09 21 10
> 
> Looking at the figma screens, group name and any text under should not be the same size.

Something else to note. I think the name will wrap into multiple lines. This should also be resolved then.

**Comment by ibencetic-CS** [comment]
Both rows should use end ellipsis if they are to long.

**Comment by MatkoTom** [comment]
Add private number to group title if chat is private

**Review by ibencetic-CS — APPROVED** [review]
LGTM

**Pull request merged**
